# Generated by Django 5.1.4 on 2024-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
